name: "publish"

on:
  release:
    types: [released]

jobs:
  build:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run test:lint
      - name: Run tests & coverage
        run: npm run coverage
        env: 
          BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
      - name: Build
        run: npm run build --if-present
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}