name: Lint, Test, Build, & Coverage

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run eslint
      run: npm run test:lint
    - name: Run tests & coverage
      run: npm run coverage
      env: 
        BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
    - run: npm run build --if-present
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN  }}
        parralel-finished: true